pipeline_name: OCR
text_type: general
use_doc_preprocessor: true
use_textline_orientation: true

SubModules:
  TextDetection:
    module_name: text_detection
    model_name: PP-OCRv4_server_det
    model_dir: null
  TextRecognition:
    module_name: text_recognition
    model_name: PP-OCRv4_server_rec
    model_dir: null
    batch_size: 1
    score_thresh: 0

SubPipelines:
  DocPreprocessor:
    pipeline_name: doc_preprocessor
    use_doc_orientation_classify: true
    use_doc_unwarping: true
    SubModules:
      DocOrientationClassify:
        module_name: doc_text_orientation
        model_name: PP-LCNet_x1_0_doc_ori
        model_dir: null
      DocUnwarping:
        module_name: image_unwarping
        model_name: UVDoc
        model_dir: null
