pipeline_name: OCR
text_type: general
use_doc_preprocessor: true
use_textline_orientation: true

SubModules:
  TextDetection:
    module_name: text_detection
    model_name: PP-OCRv4_server_det
    model_dir: null
  TextRecognition:
    module_name: text_recognition
    model_name: PP-OCRv4_server_rec
    model_dir: null
    batch_size: 1
    score_thresh: 0
